// MODIFIE ICI TES 20 PRODUITS (nom, prix, description, photo, lien Stripe)
const produits=[
  {nom:"Produit 1",prix:"30 €",description:"T-shirt Madame Chan",image:"images/produit1.jpg",stripe:"https://buy.stripe.com/3cIfZi2EX45pgIDfnwaEE00"},public:"adulte",type:"tshirt"},
  {nom:"Produit 2",prix:"00 €",description:"Décris ton produit ici.",image:"images/produit2.jpg",stripe:"https://buy.stripe.com/COLLE_TON_LIEN_2"},public:"adulte",type:"tshirt"},
  {nom:"Produit 3",prix:"00 €",description:"Décris ton produit ici.",image:"images/produit3.jpg",stripe:"https://buy.stripe.com/COLLE_TON_LIEN_3"},public:"adulte",type:"tshirt"},
  {nom:"Produit 4",prix:"00 €",description:"Décris ton produit ici.",image:"images/produit4.jpg",stripe:"https://buy.stripe.com/COLLE_TON_LIEN_4"},public:"adulte",type:"tshirt"},
  {nom:"Produit 5",prix:"00 €",description:"Décris ton produit ici.",image:"images/produit5.jpg",stripe:"https://buy.stripe.com/COLLE_TON_LIEN_5"},public:"adulte",type:"tshirt"},
  {nom:"Produit 6",prix:"00 €",description:"Décris ton produit ici.",image:"images/produit6.jpg",stripe:"https://buy.stripe.com/COLLE_TON_LIEN_6"},public:"adulte",type:"tshirt"},
  {nom:"Produit 7",prix:"00 €",description:"Décris ton produit ici.",image:"images/produit7.jpg",stripe:"https://buy.stripe.com/COLLE_TON_LIEN_7"},public:"adulte",type:"tshirt"},
  {nom:"Produit 8",prix:"00 €",description:"Décris ton produit ici.",image:"images/produit8.jpg",stripe:"https://buy.stripe.com/COLLE_TON_LIEN_8"},public:"adulte",type:"tshirt"},
  {nom:"Produit 9",prix:"00 €",description:"Décris ton produit ici.",image:"images/produit9.jpg",stripe:"https://buy.stripe.com/COLLE_TON_LIEN_9"},public:"adulte",type:"tshirt"},
  {nom:"Produit 10",prix:"00 €",description:"Décris ton produit ici.",image:"images/produit10.jpg",stripe:"https://buy.stripe.com/COLLE_TON_LIEN_10"},public:"adulte",type:"veste"},
  {nom:"Produit 11",prix:"00 €",description:"Décris ton produit ici.",image:"images/produit11.jpg",stripe:"https://buy.stripe.com/COLLE_TON_LIEN_11"},public:"adulte",type:"veste"},
  {nom:"Produit 12",prix:"00 €",description:"Décris ton produit ici.",image:"images/produit12.jpg",stripe:"https://buy.stripe.com/COLLE_TON_LIEN_12"},public:"adulte",type:"veste"},
  {nom:"Produit 13",prix:"00 €",description:"Décris ton produit ici.",image:"images/produit13.jpg",stripe:"https://buy.stripe.com/COLLE_TON_LIEN_13"},public:"adulte",type:"veste"},
  {nom:"Produit 14",prix:"00 €",description:"Décris ton produit ici.",image:"images/produit14.jpg",stripe:"https://buy.stripe.com/COLLE_TON_LIEN_14"},public:"adulte",type:"veste"},
  {nom:"Produit 15",prix:"00 €",description:"Décris ton produit ici.",image:"images/produit15.jpg",stripe:"https://buy.stripe.com/COLLE_TON_LIEN_15"},public:"adulte",type:"veste"},
  {nom:"Produit 16",prix:"00 €",description:"Décris ton produit ici.",image:"images/produit16.jpg",stripe:"https://buy.stripe.com/COLLE_TON_LIEN_16"},public:"adulte",type:"veste"},
  {nom:"Produit 17",prix:"00 €",description:"Décris ton produit ici.",image:"images/produit17.jpg",stripe:"https://buy.stripe.com/COLLE_TON_LIEN_17"},public:"enfant",type:"veste"},
  {nom:"Produit 18",prix:"00 €",description:"Décris ton produit ici.",image:"images/produit18.jpg",stripe:"https://buy.stripe.com/COLLE_TON_LIEN_18"},public:"enfant",type:"veste"},
  {nom:"Produit 19",prix:"00 €",description:"Décris ton produit ici.",image:"images/produit19.jpg",stripe:"https://buy.stripe.com/COLLE_TON_LIEN_19"},public:"enfant",type:"veste"},
  {nom:"Produit 20",prix:"00 €",description:"Décris ton produit ici.",image:"images/produit20.jpg",stripe:"https://buy.stripe.com/COLLE_TON_LIEN_20"},public:"enfant",type:"tshirt"},
];
