// MODIFIE ICI TES 20 PRODUITS (nom, prix, description, photo, lien Stripe)
const produits=[
  {nom:"Produit 1",prix:"00 €",description:"Décris ton produit ici.",image:"images/produit1.jpg",stripe:"https://buy.stripe.com/COLLE_TON_LIEN_1"},
  {nom:"Produit 2",prix:"00 €",description:"Décris ton produit ici.",image:"images/produit2.jpg",stripe:"https://buy.stripe.com/COLLE_TON_LIEN_2"},
  {nom:"Produit 3",prix:"00 €",description:"Décris ton produit ici.",image:"images/produit3.jpg",stripe:"https://buy.stripe.com/COLLE_TON_LIEN_3"},
  {nom:"Produit 4",prix:"00 €",description:"Décris ton produit ici.",image:"images/produit4.jpg",stripe:"https://buy.stripe.com/COLLE_TON_LIEN_4"},
  {nom:"Produit 5",prix:"00 €",description:"Décris ton produit ici.",image:"images/produit5.jpg",stripe:"https://buy.stripe.com/COLLE_TON_LIEN_5"},
  {nom:"Produit 6",prix:"00 €",description:"Décris ton produit ici.",image:"images/produit6.jpg",stripe:"https://buy.stripe.com/COLLE_TON_LIEN_6"},
  {nom:"Produit 7",prix:"00 €",description:"Décris ton produit ici.",image:"images/produit7.jpg",stripe:"https://buy.stripe.com/COLLE_TON_LIEN_7"},
  {nom:"Produit 8",prix:"00 €",description:"Décris ton produit ici.",image:"images/produit8.jpg",stripe:"https://buy.stripe.com/COLLE_TON_LIEN_8"},
  {nom:"Produit 9",prix:"00 €",description:"Décris ton produit ici.",image:"images/produit9.jpg",stripe:"https://buy.stripe.com/COLLE_TON_LIEN_9"},
  {nom:"Produit 10",prix:"00 €",description:"Décris ton produit ici.",image:"images/produit10.jpg",stripe:"https://buy.stripe.com/COLLE_TON_LIEN_10"},
  {nom:"Produit 11",prix:"00 €",description:"Décris ton produit ici.",image:"images/produit11.jpg",stripe:"https://buy.stripe.com/COLLE_TON_LIEN_11"},
  {nom:"Produit 12",prix:"00 €",description:"Décris ton produit ici.",image:"images/produit12.jpg",stripe:"https://buy.stripe.com/COLLE_TON_LIEN_12"},
  {nom:"Produit 13",prix:"00 €",description:"Décris ton produit ici.",image:"images/produit13.jpg",stripe:"https://buy.stripe.com/COLLE_TON_LIEN_13"},
  {nom:"Produit 14",prix:"00 €",description:"Décris ton produit ici.",image:"images/produit14.jpg",stripe:"https://buy.stripe.com/COLLE_TON_LIEN_14"},
  {nom:"Produit 15",prix:"00 €",description:"Décris ton produit ici.",image:"images/produit15.jpg",stripe:"https://buy.stripe.com/COLLE_TON_LIEN_15"},
  {nom:"Produit 16",prix:"00 €",description:"Décris ton produit ici.",image:"images/produit16.jpg",stripe:"https://buy.stripe.com/COLLE_TON_LIEN_16"},
  {nom:"Produit 17",prix:"00 €",description:"Décris ton produit ici.",image:"images/produit17.jpg",stripe:"https://buy.stripe.com/COLLE_TON_LIEN_17"},
  {nom:"Produit 18",prix:"00 €",description:"Décris ton produit ici.",image:"images/produit18.jpg",stripe:"https://buy.stripe.com/COLLE_TON_LIEN_18"},
  {nom:"Produit 19",prix:"00 €",description:"Décris ton produit ici.",image:"images/produit19.jpg",stripe:"https://buy.stripe.com/COLLE_TON_LIEN_19"},
  {nom:"Produit 20",prix:"00 €",description:"Décris ton produit ici.",image:"images/produit20.jpg",stripe:"https://buy.stripe.com/COLLE_TON_LIEN_20"},
];
